# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menu.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1107, 851)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.funNum = QtWidgets.QLineEdit(self.centralwidget)
        self.funNum.setText("")
        self.funNum.setObjectName("funNum")
        self.horizontalLayout.addWidget(self.funNum)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.xVal = QtWidgets.QLineEdit(self.centralwidget)
        self.xVal.setText("")
        self.xVal.setMaxLength(3)
        self.xVal.setFrame(True)
        self.xVal.setObjectName("xVal")
        self.horizontalLayout_2.addWidget(self.xVal)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.yVal = QtWidgets.QLineEdit(self.centralwidget)
        self.yVal.setText("")
        self.yVal.setObjectName("yVal")
        self.horizontalLayout_3.addWidget(self.yVal)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.delVal = QtWidgets.QComboBox(self.centralwidget)
        self.delVal.setObjectName("delVal")
        self.delVal.addItem("")
        self.delVal.addItem("")
        self.delVal.addItem("")
        self.horizontalLayout_4.addWidget(self.delVal)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem9)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.epiVal = QtWidgets.QComboBox(self.centralwidget)
        self.epiVal.setObjectName("epiVal")
        self.epiVal.addItem("")
        self.epiVal.addItem("")
        self.epiVal.addItem("")
        self.epiVal.addItem("")
        self.horizontalLayout_5.addWidget(self.epiVal)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem11)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem12)
        self.rot = QtWidgets.QComboBox(self.centralwidget)
        self.rot.setObjectName("rot")
        self.rot.addItem("")
        self.rot.addItem("")
        self.horizontalLayout_6.addWidget(self.rot)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem13)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem14)
        self.nVal = QtWidgets.QLineEdit(self.centralwidget)
        self.nVal.setText("")
        self.nVal.setObjectName("nVal")
        self.horizontalLayout_7.addWidget(self.nVal)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem15)
        self.subBut = QtWidgets.QPushButton(self.centralwidget)
        self.subBut.setObjectName("subBut")
        self.verticalLayout.addWidget(self.subBut)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem16)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.verticalLayout)
        self.op = QtWidgets.QTextBrowser(self.centralwidget)
        self.op.setObjectName("op")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.op)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Functions</p><p>1) (x-2)<span style=\" vertical-align:super;\">2 </span>+(y-2)<span style=\" vertical-align:super;\">2</span> [Circle]</p><p>2) 0.26(x<span style=\" vertical-align:super;\">2</span>+y<span style=\" vertical-align:super;\">2</span>)-0.48xy [Matyas Function]</p><p>3) (1-x)<span style=\" vertical-align:super;\">2</span>+100(y-x<span style=\" vertical-align:super;\">2</span>)<span style=\" vertical-align:super;\">2</span> [Rosenbrock Valley Function]</p><p>4) (1.5-x+xy)<span style=\" vertical-align:super;\">2</span>+(2.25-x+xy<span style=\" vertical-align:super;\">2</span>)<span style=\" vertical-align:super;\">2</span>+(2.625-x+xy<span style=\" vertical-align:super;\">3</span>)<span style=\" vertical-align:super;\">2</span> [Beale Function]</p><p>5) (x+2y-7)<span style=\" vertical-align:super;\">2</span>+(2x_y-5)<span style=\" vertical-align:super;\">2</span>  [Booth Function]</p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "Function"))
        self.funNum.setInputMask(_translate("MainWindow", "9"))
        self.funNum.setPlaceholderText(_translate("MainWindow", "Enter function number"))
        self.label.setText(_translate("MainWindow", "x value"))
        self.xVal.setInputMask(_translate("MainWindow", "009"))
        self.xVal.setPlaceholderText(_translate("MainWindow", "x value"))
        self.label_2.setText(_translate("MainWindow", "y value"))
        self.yVal.setInputMask(_translate("MainWindow", "009"))
        self.yVal.setPlaceholderText(_translate("MainWindow", "y value"))
        self.label_3.setText(_translate("MainWindow", "Delta"))
        self.delVal.setItemText(0, _translate("MainWindow", "0.5"))
        self.delVal.setItemText(1, _translate("MainWindow", "0.05"))
        self.delVal.setItemText(2, _translate("MainWindow", "0.005"))
        self.label_4.setText(_translate("MainWindow", "Epsilon"))
        self.epiVal.setItemText(0, _translate("MainWindow", "0.1"))
        self.epiVal.setItemText(1, _translate("MainWindow", "0.01"))
        self.epiVal.setItemText(2, _translate("MainWindow", "0.001"))
        self.epiVal.setItemText(3, _translate("MainWindow", "0.0001"))
        self.label_8.setText(_translate("MainWindow", "Rotations"))
        self.rot.setItemText(0, _translate("MainWindow", "4"))
        self.rot.setItemText(1, _translate("MainWindow", "8"))
        self.label_5.setText(_translate("MainWindow", "Iterations"))
        self.nVal.setInputMask(_translate("MainWindow", "009"))
        self.nVal.setPlaceholderText(_translate("MainWindow", "n value"))
        self.subBut.setText(_translate("MainWindow", "Submit"))

